id: 7c5f1c809f5d49d5aeb5fdcf277da76f
initial_creation_type: ocr
source_metadata:
  volumes:
    35e11576687e4ea98ec0190e047d66b2:
      base_file: v091.txt
      image_group_id: I1PD95937
      title: ''
      total_pages: 1728
      volume_number: 92
